### ISSUE TITLE
merge efforts with PdbTool.jl?

### ISSUE THREAD

**Issue by carlobaldassi** [hng/BiomolecularStructures.jl#18]
The [PdbTool.jl](https://github.com/christophfeinauer/PdbTool.jl) Julia package was already providing a way to deal with PDB files.
It seems to me that efforts could be made to have all PDB-related functionality in a single package if possible.

cc: @christophfeinauer

**Comment by gp0** [comment]
Yup, we're using a haphazard way to read PDB files anyway (BioPython). As a matter of fact, i simply didn't know about the PdbTool.jl until about 2 or 3 days ago :smile: .

It wouldn't take much effort to get rid of the BioPython calls and to use PdbTool for that.

**Comment by gp0** [comment]
We're using PdbTool.jl to read PDB files as of now, so there should be no duplicate functionality anymore.

**Comment by carlobaldassi** [comment]
Great!
