### ISSUE TITLE
rename repo/package?

### ISSUE THREAD

**Issue by gp0** [hng/BiomolecularStructures.jl#6]
See: http://julia.readthedocs.org/en/latest/manual/packages/#guidelines-for-naming-a-package

**Comment by DanielHoffmann32** [comment]
Vielleicht BiomolecularStructures?

**Comment by gp0** [comment]
Finde ich gut!

**Comment by hng** [comment]
Habe das Repo zu BiomolecularStructures.jl umbenannt. Ggf. später noch mal schauen ob sich ein weiteres Aufteilen in mehrere Pakete lohnt.
